// category
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const RESET_CATEGORY = 'RESET_CATEGORY'
// menu
export const FETCH_MENU = 'FETCH_MENU'
export const FETCH_MENU_PENDING = 'FETCH_MENU_PENDING'
export const FETCH_MENU_FULFILLED = 'FETCH_MENU_FULFILLED'
export const FETCH_MENU_REJECTED = 'FETCH_MENU_REJECTED'
export const FETCH_MENU_TIMEOUT = 'FETCH_MENU_TIMEOUT'
export const DROP_PRODUCT = 'DROP_PRODUCT'
export const DROP_CATEGORY = 'DROP_CATEGORY'
export const DROP_ADDITIONAL_PRODUCT = 'DROP_ADDITIONAL_PRODUCT'
export const DROP_ADDITIONAL_CATEGORY = 'DROP_ADDITIONAL_CATEGORY'
export const REMOVE_MENU_ITEM = 'REMOVE_MENU_ITEM'
export const REMOVE_MENU_ITEM_FULFILLED = 'REMOVE_MENU_ITEM_FULFILLED'
export const REMOVE_MENU_ITEM_REJECTED = 'REMOVE_MENU_ITEM_REJECTED'
export const UPDATE_MENU_ITEM = 'UPDATE_MENU_ITEM'
export const UPDATE_MENU_ITEM_FULFILLED = 'UPDATE_MENU_ITEM_FULFILLED'
export const UPDATE_MENU_ITEM_REJECTED = 'UPDATE_MENU_ITEM_REJECTED'
export const CREATE_MENU_ITEM = 'CREATE_MENU_ITEM'
export const CREATE_MENU_ITEM_FULFILLED = 'CREATE_MENU_ITEM_FULFILLED'
export const CREATE_MENU_ITEM_REJECTED = 'CREATE_MENU_ITEM_REJECTED'

// nomenclature
export const FETCH_NOMENCLATURE = 'FETCH_NOMENCLATURE'
export const FETCH_NOMENCLATURE_PENDING = 'FETCH_NOMENCLATURE_PENDING'
export const FETCH_NOMENCLATURE_FULFILLED = 'FETCH_NOMENCLATURE_FULFILLED'
export const FETCH_NOMENCLATURE_REJECTED = 'FETCH_NOMENCLATURE_REJECTED'
export const FETCH_NOMENCLATURE_TIMEOUT = 'FETCH_NOMENCLATURE_TIMEOUT'
// view
export const SHOW_MENU_EDIT_MODAL = 'SHOW_MENU_EDIT_MODAL'
export const HIDE_MENU_EDIT_MODAL = 'HIDE_MENU_EDIT_MODAL'

//path
export const CHANGE_MENU_LEVEL = 'CHANGE_MENU_LEVEL'